 export const coreproducts = [
   {
     image: "images/products/athletic-cotton-socks-6-pairs.jpg",
     name: "Black and Gray Athletic Cotton Socks - 6 Pairs",
     rating: {
       stars: 4.5,
       count: 87,
     },
     price: 1090,
     keywords: ["socks", "sports", "apparel"],
   },
   {
     image: "images/products/intermediate-composite-basketball.jpg",
     name: "Intermediate Size Basketball",
     rating: {
       stars: 4,
       count: 127,
     },
     price: 2095,
     keywords: ["sports", "basketballs"],
   },
   {
     image: "images/products/adults-plain-cotton-tshirt-2-pack-teal.jpg",
     name: "Adults Plain Cotton T-Shirt - 2 Pack",
     rating: {
       stars: 4.5,
       count: 56,
     },
     price: 799,
     keywords: ["tshirts", "apparel", "mens"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/adults-plain-cotton-tshirt-2-pack-red.jpg",
     name: "Adults Plain Cotton T-Shirt - 2 Pack",
     rating: {
       stars: 4.5,
       count: 76,
     },
     price: 829,
     keywords: ["tshirts", "apparel", "mens"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/adults-plain-cotton-tshirt-2-pack-black.jpg",
     name: "Adults Plain Cotton T-Shirt - 2 Pack",
     rating: {
       stars: 3.5,
       count: 46,
     },
     price: 599,
     keywords: ["tshirts", "apparel", "mens"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/adults-plain-cotton-tshirt-2-pack-plus-black.jpg",
     name: "Adults Plain Cotton T-Shirt (plus) - 2 Pack",
     rating: {
       stars: 4.5,
       count: 113,
     },
     price: 899,
     keywords: ["tshirts", "apparel", "mens"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/black-2-slot-toaster.jpg",
     name: "2 Slot Toaster - Black",
     rating: {
       stars: 5,
       count: 2197,
     },
     price: 1899,
     keywords: ["toaster", "kitchen", "appliances"],
   },
   {
     image: "images/products/6-piece-white-dinner-plate-set.jpg",
     name: "6 Piece White Dinner Plate Set",
     rating: {
       stars: 4,
       count: 37,
     },
     price: 2067,
     keywords: ["plates", "kitchen", "dining"],
   },
   {
     image: "images/products/6-piece-non-stick-baking-set.webp",
     name: "6-Piece Nonstick, Carbon Steel Oven Bakeware Baking Set",
     rating: {
       stars: 4.5,
       count: 175,
     },
     price: 3499,
     keywords: ["kitchen", "cookware"],
   },
   {
     image: "images/products/men-chino-pants-black.jpg",
     name: "Men's Classic-fit Pleated Chino Pants",
     rating: {
       stars: 4.5,
       count: 9017,
     },
     price: 2290,
     keywords: ["pants", "apparel", "mens"],
   },
   {
     image: "images/products/men-chino-pants-green.jpg",
     name: "Men's Classic-fit Pleated Chino Pants",
     rating: {
       stars: 4.5,
       count: 9017,
     },
     price: 2290,
     keywords: ["pants", "apparel", "mens"],
   },
   {
     image: "images/products/plain-hooded-fleece-sweatshirt-yellow.jpg",
     name: "Plain Hooded Fleece Sweatshirt",
     rating: {
       stars: 4.5,
       count: 317,
     },
     price: 2400,
     keywords: ["hoodies", "sweaters", "apparel"],
   },
   {
     image: "images/products/luxury-tower-set-6-piece.jpg",
     name: "Luxury Towel Set - Graphite Gray",
     rating: {
       stars: 4.5,
       count: 144,
     },
     price: 3599,
     keywords: ["bathroom", "washroom", "restroom", "towels", "bath towels"],
   },
   {
     image: "images/products/luxury-tower-set-4-piece.jpg",
     name: "Luxury Towel Set - Graphite Gray",
     rating: {
       stars: 4.5,
       count: 344,
     },
     price: 2799,
     keywords: ["bathroom", "washroom", "restroom", "towels", "bath towels"],
   },
   {
     image: "images/products/plain-hooded-fleece-sweatshirt-teal.jpg",
     name: "Plain Hooded Fleece Sweatshirt",
     rating: {
       stars: 4.5,
       count: 317,
     },
     price: 2400,
     keywords: ["hoodies", "sweaters", "apparel"],
   },
   {
     image: "images/products/liquid-laundry-detergent-plain.jpg",
     name: "Liquid Laundry Detergent, 110 Loads, 82.5 Fl Oz",
     rating: {
       stars: 4.5,
       count: 305,
     },
     price: 2899,
     keywords: ["bathroom", "cleaning"],
   },
   {
     image: "images/products/liquid-laundry-detergent-lavender.jpg",
     name: "Liquid Laundry Detergent, 110 Loads, 82.5 Fl Oz",
     rating: {
       stars: 4.5,
       count: 305,
     },
     price: 2499,
     keywords: ["bathroom", "cleaning"],
   },
   {
     image: "images/products/knit-athletic-sneakers-gray.jpg",
     name: "Waterproof Knit Athletic Sneakers - Gray",
     rating: {
       stars: 4,
       count: 89,
     },
     price: 3390,
     keywords: ["shoes", "running shoes", "footwear"],
   },
   {
     image: "images/products/women-chiffon-beachwear-coverup-black.jpg",
     name: "Women's Chiffon Beachwear Cover Up - Black",
     rating: {
       stars: 4.5,
       count: 235,
     },
     price: 2070,
     keywords: ["robe", "swimsuit", "swimming", "bathing", "apparel"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/round-sunglasses-black.jpg",
     name: "Round Sunglasses",
     rating: {
       stars: 4.5,
       count: 30,
     },
     price: 1560,
     keywords: ["accessories", "shades"],
   },
   {
     image: "images/products/round-sunglasses-gold.jpg",
     name: "Round Sunglasses",
     rating: {
       stars: 4.5,
       count: 30,
     },
     price: 1560,
     keywords: ["accessories", "shades"],
   },
   {
     image: "images/products/women-beach-sandals.jpg",
     name: "Women's Two Strap Buckle Sandals - Tan",
     rating: {
       stars: 4.5,
       count: 562,
     },
     price: 2499,
     keywords: ["footwear", "sandals", "womens", "beach", "summer"],
   },
   {
     image: "images/products/blackout-curtain-set-beige.webp",
     name: "Blackout Curtains Set 4-Pack - Beige",
     rating: {
       stars: 4.5,
       count: 232,
     },
     price: 4599,
     keywords: ["bedroom", "curtains", "home"],
   },
   {
     image: "images/products/men-slim-fit-summer-shorts-gray.jpg",
     name: "Men's Slim-Fit Summer Shorts",
     rating: {
       stars: 4,
       count: 160,
     },
     price: 1699,
     keywords: ["shorts", "apparel", "mens"],
   },
   {
     image: "images/products/men-slim-fit-summer-shorts-beige.jpg",
     name: "Men's Slim-Fit Summer Shorts",
     rating: {
       stars: 4,
       count: 160,
     },
     price: 1699,
     keywords: ["shorts", "apparel", "mens"],
   },
   {
     image: "images/products/electric-glass-and-steel-hot-water-kettle.webp",
     name: "Electric Glass and Steel Hot Tea Water Kettle - 1.7-Liter",
     rating: {
       stars: 5,
       count: 846,
     },
     price: 3074,
     keywords: ["water boiler", "appliances", "kitchen"],
   },
   {
     image: "images/products/facial-tissue-2-ply-18-boxes.jpg",
     name: "Ultra Soft Tissue 2-Ply - 18 Box",
     rating: {
       stars: 4,
       count: 99,
     },
     price: 2374,
     keywords: ["kleenex", "tissues", "kitchen", "tissues box", "napkins"],
   },
   {
     image: "images/products/straw-sunhat.webp",
     name: "Straw Lifeguard Sun Hat",
     rating: {
       stars: 4,
       count: 215,
     },
     price: 2200,
     keywords: ["hats", "straw hats", "summer", "apparel"],
   },
   {
     image: "images/products/men-golf-polo-t-shirt-black.jpg",
     name: "Men's Regular-Fit Quick-Dry Golf Polo Shirt",
     rating: {
       stars: 4.5,
       count: 2556,
     },
     price: 1599,
     keywords: ["tshirts", "shirts", "apparel", "mens"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/sky-flower-stud-earrings.webp",
     name: "Sterling Silver Sky Flower Stud Earrings",
     rating: {
       stars: 4.5,
       count: 52,
     },
     price: 1799,
     keywords: ["jewelry", "accessories", "womens"],
   },
   {
     image: "images/products/women-stretch-popover-hoodie-black.jpg",
     name: "Women's Stretch Popover Hoodie",
     rating: {
       stars: 4.5,
       count: 2465,
     },
     price: 1374,
     keywords: ["hooded", "hoodies", "sweaters", "womens", "apparel"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/women-stretch-popover-hoodie-blue.jpg",
     name: "Women's Stretch Popover Hoodie",
     rating: {
       stars: 4.5,
       count: 2465,
     },
     price: 1374,
     keywords: ["hooded", "hoodies", "sweaters", "womens", "apparel"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/men-golf-polo-t-shirt-red.jpg",
     name: "Men's Regular-Fit Quick-Dry Golf Polo Shirt",
     rating: {
       stars: 4.5,
       count: 2556,
     },
     price: 1599,
     keywords: ["tshirts", "shirts", "apparel", "mens"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/men-slim-fit-summer-shorts-black.jpg",
     name: "Men's Slim-Fit Summer Shorts",
     rating: {
       stars: 4,
       count: 160,
     },
     price: 1699,
     keywords: ["shorts", "apparel", "mens"],
   },
   {
     image: "images/products/bathroom-rug.jpg",
     name: "Bathroom Bath Rug Mat 20 x 31 Inch - Grey",
     rating: {
       stars: 4.5,
       count: 119,
     },
     price: 1250,
     keywords: ["bathmat", "bathroom", "home"],
   },
   {
     image: "images/products/women-knit-ballet-flat-black.jpg",
     name: "Women's Knit Ballet Flat",
     rating: {
       stars: 4,
       count: 326,
     },
     price: 2640,
     keywords: ["shoes", "flats", "womens", "footwear"],
   },
   {
     image: "images/products/men-cozy-fleece-zip-up-hoodie-black.jpg",
     name: "Men's Full-Zip Hooded Fleece Sweatshirt",
     rating: {
       stars: 4.5,
       count: 3017,
     },
     price: 2500,
     keywords: ["sweaters", "hoodies", "apparel", "mens"],
   },
   {
     image: "images/products/women-stretch-popover-hoodie-gray.jpg",
     name: "Women's Stretch Popover Hoodie",
     rating: {
       stars: 4.5,
       count: 2465,
     },
     price: 1374,
     keywords: ["hooded", "hoodies", "sweaters", "womens", "apparel"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/men-golf-polo-t-shirt-blue.jpg",
     name: "Men's Regular-Fit Quick-Dry Golf Polo Shirt",
     rating: {
       stars: 4.5,
       count: 2556,
     },
     price: 1599,
     keywords: ["tshirts", "shirts", "apparel", "mens"],
     type: "clothing",
     sizeChartLink: "images/clothing-size-chart.png",
   },
   {
     image: "images/products/women-knit-ballet-flat-gray.jpg",
     name: "Women's Knit Ballet Flat",
     rating: {
       stars: 4,
       count: 326,
     },
     price: 2640,
     keywords: ["shoes", "flats", "womens", "footwear"],
   },
   {
     image: "images/products/trash-can-with-foot-pedal-50-liter.jpg",
     name: "Trash Can with Foot Pedal - Brushed Stainless Steel",
     rating: {
       stars: 4.5,
       count: 2286,
     },
     price: 8300,
     keywords: ["garbage", "bins", "cans", "kitchen"],
   },
   {
     image: "images/products/trash-can-with-foot-pedal-30-liter-tall.jpg",
     name: "Trash Can with Foot Pedal (30l) - Brushed Stainless Steel",
     rating: {
       stars: 4.5,
       count: 2286,
     },
     price: 8300,
     keywords: ["garbage", "bins", "cans", "kitchen"],
   },
   {
     image: "images/products/duvet-cover-set-blue-twin.jpg",
     name: "Duvet Cover Set with Zipper Closure",
     rating: {
       stars: 4,
       count: 456,
     },
     price: 2399,
     keywords: ["bedroom", "bed sheets", "sheets", "covers", "home"],
   },
   {
     image: "images/products/duvet-cover-set-blue-queen.jpg",
     name: "Duvet (Queen size) Cover Set with Zipper Closure",
     rating: {
       stars: 4.5,
       count: 706,
     },
     price: 3499,
     keywords: ["bedroom", "bed sheets", "sheets", "covers", "home"],
   },
   {
     image: "images/products/women-knit-ballet-flat-leopard.jpg",
     name: "Women's Knit Ballet Flat",
     rating: {
       stars: 4,
       count: 326,
     },
     price: 2640,
     keywords: ["shoes", "flats", "womens", "footwear"],
   },
   {
     image: "images/products/women-chunky-beanie-gray.webp",
     name: "Women's Chunky Cable Beanie - Gray",
     rating: {
       stars: 5,
       count: 83,
     },
     price: 1250,
     keywords: [
       "hats",
       "winter hats",
       "beanies",
       "tuques",
       "apparel",
       "womens",
     ],
   },
   {
     image: "images/products/men-chino-pants-beige.jpg",
     name: "Men's Classic-fit Pleated Chino Pants",
     rating: {
       stars: 4.5,
       count: 9017,
     },
     price: 2290,
     keywords: ["pants", "apparel", "mens"],
   },
   {
     image: "images/products/duvet-cover-set-red-twin.jpg",
     name: "Duvet Cover Set with Zipper Closure (red)",
     rating: {
       stars: 2.5,
       count: 149,
     },
     price: 1899,
     keywords: ["bedroom", "bed sheets", "sheets", "covers", "home"],
   },
   {
     image: "images/products/duvet-cover-set-red-queen.jpg",
     name: "Duvet (queen size) Cover Set with Zipper Closure (red)",
     rating: {
       stars: 3.5,
       count: 279,
     },
     price: 2899,
     keywords: ["bedroom", "bed sheets", "sheets", "covers", "home"],
   },
   {
     image: "images/products/men-athletic-shoes-green.jpg",
     name: "Men's Athletic Sneaker",
     rating: {
       stars: 4,
       count: 229,
     },
     price: 3890,
     keywords: ["shoes", "running shoes", "footwear", "mens"],
   },
   {
     image: "images/products/men-athletic-shoes-black.jpg",
     name: "Men's Athletic Sneaker",
     rating: {
       stars: 4.5,
       count: 239,
     },
     price: 3800,
     keywords: ["shoes", "running shoes", "footwear", "mens"],
   },
   {
     image: "images/products/men-navigator-sunglasses-brown.jpg",
     name: "Men's Navigator Sunglasses Pilot",
     rating: {
       stars: 3.5,
       count: 42,
     },
     price: 1690,
     keywords: ["sunglasses", "glasses", "accessories", "shades"],
   },
   {
     image: "images/products/men-navigator-sunglasses-silver.jpg",
     name: "Men's Navigator Sunglasses Pilot",
     rating: {
       stars: 3.5,
       count: 42,
     },
     price: 1690,
     keywords: ["sunglasses", "glasses", "accessories", "shades"],
   },
   {
     image: "images/products/non-stick-cooking-set-15-pieces.webp",
     name: "Non-Stick Cookware Set, Pots, Pans and Utensils - 15 Pieces",
     rating: {
       stars: 4.5,
       count: 511,
     },
     price: 6797,
     keywords: ["cooking set", "kitchen"],
   },
   {
     image: "images/products/vanity-mirror-silver.jpg",
     name: "Vanity Mirror with Heavy Base - Chrome",
     rating: {
       stars: 4.5,
       count: 130,
     },
     price: 1649,
     keywords: ["bathroom", "washroom", "mirrors", "home"],
   },
   {
     image: "images/products/women-french-terry-fleece-jogger-camo.jpg",
     name: "Women's Fleece Jogger Sweatpant",
     rating: {
       stars: 4.5,
       count: 248,
     },
     price: 2400,
     keywords: ["pants", "sweatpants", "jogging", "apparel", "womens"],
   },
   {
     image: "images/products/women-french-terry-fleece-jogger-gray.jpg",
     name: "Women's Fleece Jogger Sweatpant",
     rating: {
       stars: 4.5,
       count: 248,
     },
     price: 2400,
     keywords: ["pants", "sweatpants", "jogging", "apparel", "womens"],
   },
   {
     image: "images/products/double-elongated-twist-french-wire-earrings.webp",
     name: "Double Oval Twist French Wire Earrings - Gold",
     rating: {
       stars: 4.5,
       count: 117,
     },
     price: 2400,
     keywords: ["accessories", "womens"],
   },
   {
     image: "images/products/round-airtight-food-storage-containers.jpg",
     name: "Round Airtight Food Storage Containers - 5 Piece",
     rating: {
       stars: 4,
       count: 126,
     },
     price: 2899,
     keywords: ["boxes", "food containers", "kitchen"],
   },
   {
     image: "images/products/coffeemaker-with-glass-carafe-black.jpg",
     name: "Coffeemaker with Glass Carafe and Reusable Filter - 25 Oz, Black",
     rating: {
       stars: 4.5,
       count: 1211,
     },
     price: 2250,
     keywords: ["coffeemakers", "kitchen", "appliances"],
   },
   {
     image: "images/products/blackout-curtains-black.jpg",
     name: "Blackout Curtains Set 42 x 84-Inch - Black, 2 Panels",
     rating: {
       stars: 4.5,
       count: 363,
     },
     price: 3099,
     keywords: ["bedroom", "home"],
   },
   {
     image: "images/products/cotton-bath-towels-teal.webp",
     name: "100% Cotton Bath Towels - 2 Pack, Light Teal",
     rating: {
       stars: 4.5,
       count: 93,
     },
     price: 2110,
     keywords: ["bathroom", "home", "towels"],
   },
   {
     image: "images/products/knit-athletic-sneakers-pink.webp",
     name: "Waterproof Knit Athletic Sneakers - Pink",
     rating: {
       stars: 4,
       count: 89,
     },
     price: 3390,
     keywords: ["shoes", "running shoes", "footwear", "womens"],
   },
   {
     image: "images/products/countertop-blender-64-oz.jpg",
     name: "Countertop Blender - 64oz, 1400 Watts",
     rating: {
       stars: 4,
       count: 3,
     },
     price: 10747,
     keywords: ["food blenders", "kitchen", "appliances"],
   },
   {
     image: "images/products/floral-mixing-bowl-set.jpg",
     name: "10-Piece Mixing Bowl Set with Lids - Floral",
     rating: {
       stars: 5,
       count: 679,
     },
     price: 3899,
     keywords: ["mixing bowls", "baking", "cookware", "kitchen"],
   },
   {
     image: "images/products/kitchen-paper-towels-30-pack.jpg",
     name: "2-Ply Kitchen Paper Towels - 30 Pack",
     rating: {
       stars: 4.5,
       count: 1045,
     },
     price: 5799,
     keywords: ["kitchen", "kitchen towels", "tissues"],
   },
   {
     image: "images/products/men-cozy-fleece-zip-up-hoodie-red.jpg",
     name: "Men's Full-Zip Hooded Fleece Sweatshirt",
     rating: {
       stars: 4.5,
       count: 3157,
     },
     price: 2400,
     keywords: ["sweaters", "hoodies", "apparel", "mens"],
   },
 ];
